GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/6070b88ed4f331fd070ae29c
###
GET http://localhost:3001/api/persons/invalidID
###
DELETE http://localhost:3001/api/persons/60742d6ebb591f3f319462b6
###
DELETE http://localhost:3001/api/persons/invalidID
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "foo",
    "number": "123-456-789"
}
###
PUT http://localhost:3001/api/persons/6070b88ed4f331fd070ae29c
Content-Type: application/json

{
    "name": "foo",
    "number": "565"
}